# Generated by Django 5.2.1 on 2025-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_conversation_message_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('performer', 'Performer'), ('organizer', 'Organizer')], max_length=20),
        ),
    ]
